---
- name: Deploy Application
  hosts: all
  tasks:
    - name: Transfer WAR File
      ansible.builtin.copy:
        src: target/MyWebApp.war
        dest: /tmp/
        remote_src: yes

    - name: Restart Application
      service:
        name: tomcat
        state: restarted
