---
- name: Deploy Application
  hosts: all
  tasks:
    - name: Transfer WAR File
      ansible.builtin.copy:
        src: /home/runner/work/Ansible/Ansible/target/MyApp.war
        dest: /opt/tomcat/webapps/MyApp.war

    - name: Restart Application
      service:
        name: tomcat
        state: restarted
