---
- name: Deploy Application #deploy
  hosts: all
  tasks:
    - name: Transfer WAR File
      ansible.builtin.copy:
        src: /home/runner/work/Ansible_test1/Ansible_test1/artifact/*.war
        dest: /tmp/*.war

    - name: Restart Application
      service:
        name: tomcat
        state: restarted
