---
- name: Deploy Application
  hosts: all
  tasks:
    - name: Transfer WAR File
      ansible.builtin.copy:
        src: /home/runner/work/Ansible_test1/Ansible_test1/target/MyWebApp.war
        dest: /tmp/

    - name: Restart Application
      service:
        name: tomcat
        state: restarted
