---
- name: Deploy Application
  hosts: all
  become: true
  tasks:
        
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Java
      apt:
        name: openjdk-11-jdk
        state: present

    - name: Install Tomcat
      apt:
        name: tomcat8
        state: present

    - name: Ensure Tomcat is running    
      service:
        name: tomcat8
        state: started
        enabled: true
        
    - name: Transfer WAR File
      ansible.builtin.copy:
        src: /home/runner/work/Ansible_test1/Ansible_test1/artifact/MyWebApp.war
        dest: /var/lib/tomcat9/webapps/MyWebApp.war

    - name: Restart Application
      service:
        name: tomcat8
        state: restarted
