name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.REMOTE_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy and Install Software on EC2
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            # Print debugging information
            ssh -vvv ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}    

      - name: Deploy Application via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Update package list and install prerequisites
            sudo apt-get update -y
            sudo apt-get install -y openjdk-11-jdk memcached wget

            # Install Jetty 9.4.46 if not already installed
            if [ ! -d /opt/jetty ]; then
              wget https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-distribution/9.4.46.v20220331/jetty-distribution-9.4.46.v20220331.tar.gz -O /tmp/jetty.tar.gz
              sudo tar -xzvf /tmp/jetty.tar.gz -C /opt/
              sudo mv /opt/jetty-distribution-9.4.46.v20220331 /opt/jetty
            fi

            # Install ActiveMQ if not already installed
            if [ ! -d /opt/activemq ]; then
              wget https://archive.apache.org/dist/activemq/5.16.3/apache-activemq-5.16.3-bin.tar.gz -O /tmp/activemq.tar.gz
              sudo tar -xzvf /tmp/activemq.tar.gz -C /opt/
              sudo mv /opt/apache-activemq-5.16.3 /opt/activemq
            fi

            # Download the application artifact from Artifactory
            sudo cp /home/runner/work/Ansible_test1/Ansible_test1/artifact/MyWebApp.war -O /tmp/MyWebApp.war

            # Deploy the WAR file into Jetty's webapps directory
            sudo cp /tmp/MyWebApp.war /opt/jetty/webapps/

            # Optionally, start memcached (if not already running)
            sudo systemctl start memcached

            # Optionally, start Jetty and ActiveMQ if required:
            sudo /opt/jetty/bin/jetty.sh start
            sudo /opt/activemq/bin/activemq start
