name: Build and Deploy

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      JAVA_HOME: /usr/java/jdk1.8.0_171/
      MAVEN_HOME: /opt/maven/apache-maven-3.2.2
      PATH: $JAVA_HOME/bin:$MAVEN_HOME/bin:$PATH

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up SSH key (if needed)
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Clone Repository via SSH
        run: |
          git clone --branch dev ssh://git@stash.barnesandnoble.com:7777/nook_cloud_eng/bncloud.git

      - name: Build with Maven
        run: |
          cd bncloud
          mvn -f pom.xml -e -Pjenkins -Djunit \
          -Dbuild.id=$GITHUB_JOB-$GITHUB_RUN_NUMBER \
          -Dscm.rev=$GITHUB_SHA \
          -Dscm.branch=$GITHUB_REF_NAME \
          -Dbuild.date=$(date +%Y%m%d%H%M%S) \
          clean deploy -DskipTests

      - name: Archive Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            **/target/*.zip
            **/target/BNC-L10n*.jar
            **/target/BNC-JettyCustomization*.jar
            **/target/*Web*.war
            **/target/BNC-Mock-Partners*.war
