name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    env:
      PATH: C:\Program Files\Git\usr\bin:${{ env.PATH }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4
        with:
          maven-version: '3.2.2'

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        env:
          PATH: C:\Program Files\Git\usr\bin:${{ env.PATH }}

      - name: Clone Repository via SSH
        run: |
          git clone --branch dev ssh://git@stash.barnesandnoble.com:7777/nook_cloud_eng/bncloud.git

      - name: Build with Maven
        run: |
          cd bncloud
          mvn -f pom.xml -e -Pjenkins -Djunit \
          -Dbuild.id=$GITHUB_JOB-$GITHUB_RUN_NUMBER \
          -Dscm.rev=$GITHUB_SHA \
          -Dscm.branch=$GITHUB_REF_NAME \
          -Dbuild.date=$(date +%Y%m%d%H%M%S) \
          clean deploy -DskipTests

      - name: Archive Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            **/target/*.zip
            **/target/BNC-L10n*.jar
            **/target/BNC-JettyCustomization*.jar
            **/target/*Web*.war
            **/target/BNC-Mock-Partners*.war
