pipeline:
  agent:
    label: any
 
  environment:
    JAVA_HOME: /usr/java/jdk1.8.0_171/
    MAVEN_HOME: /opt/maven/apache-maven-3.2.2
    PATH: "$JAVA_HOME/bin:$MAVEN_HOME/bin:$PATH"
 
  stages:
    - stage: Checkout
      steps:
        - checkout:
            scm:
              git:
                url: "ssh://git@stash.barnesandnoble.com:7777/nook_cloud_eng/bncloud.git"
                credentialsId: "your-ssh-credentials-id"
                branch: "dev"
                browser:
                  type: "stash"
                  url: "http://stash.barnesandnoble.com/projects/NOOK_CLOUD_ENG/repos/bncloud/"
 
    - stage: Build
      steps:
        - sh: >
            mvn -f pom.xml -e -Pjenkins -Djunit 
            -Dbuild.id=$JOB_NAME-$BUILD_NUMBER 
            -Dscm.rev=$GIT_COMMIT 
            -Dscm.branch=$GIT_BRANCH 
            -Dbuild.date=$BUILD_ID 
            clean deploy -DskipTests
 
    - stage: Archive Artifacts
      steps:
        - archiveArtifacts:
            artifacts: '**/target/*.zip, **/target/BNC-L10n*.jar, **/target/BNC-JettyCustomization*.jar, **/target/*Web*.war, **/target/BNC-Mock-Partners*.war'
            fingerprint: true
